### ISSUE TITLE
Run setup.sh in basler drivers before build

### ISSUE THREAD

**Issue by JanGut** [bit-bots/bitbots_meta#13]
The basler drivers package requires running a setup script on the robot before build. This script currently depends on a internet connection. Please implement this somehow in the robot compile script.

**Comment by timonegk** [comment]
This should also be possible for the own computer via `make basler` for example

**Comment by timonegk** [comment]
> This should also be possible for the own computer via `make basler` for example

This was done in da4f79cb45431e11d1e088b8f010b82b33d62744

**Comment by timonegk** [comment]
> This script currently depends on a internet connection. Please implement this somehow in the robot compile script.
This happened already.

**Comment by ftsell** [comment]
This should be placed in our ansible repo
