### ISSUE TITLE
Resolve dependency on `wolfgang_webots_sim`

### ISSUE THREAD

**Issue by jaagut** [bit-bots/bitbots_meta#187]
Currently, `bitbots_bringup` and `bitbots_test` depend on `wolfgang_webots_sim`, which is why using rosdep on the robots failed. Now, we temporarily included `wolfgang_webots_sim` in the sync-includes, but this is not optimal. See #186 

## Expected behavior
Rosdep should not complain about missing dependencies.
`wolfgang_webots_sim` should not be synced to the robots

## Current behavior
We sync `wolfgang_webots_sim` to the robots.

## Context (Environment)

- [ ] RViz
- [ ] Simulator
- [X] Robot
- [ ] Local

## Possible Solution
???

**Comment by Flova** [comment]
Sadly, ROS does not support optional dependencies. So we could either copy it to the robot or don't include it as a dep. Both have advantages and disadvantages. Including it as a dep would make sure it is build correctly in all cases on the local machine. But copying it on the robot takes unnecessary time during sync and build. I would vote for it being synced.

**Comment by jaagut** [comment]
@timonegk suggested using a conditional dependency. See here https://www.ros.org/reps/rep-0149.html#dependency-tags
