### ISSUE TITLE
docs: ROS Messages not always importable

### ISSUE THREAD

**Issue by ftsell** [bit-bots/bitbots_meta#232]
When building documentation errors like
```
WARNING: autodoc: failed to import module 'monitor' from module 'system_monitor'; the following exception was raised:
No module named 'system_monitor.msg'
```
indicate that messages are not correctly importable.

## Expected behavior
Message imports should not stop sphinx from building documentation

## Current behavior
No documentation for the affected module is generated

## Possible Solution
When the message is imported in the sphinx projects `conf.py` file, all message imports are resolvable.

This is very weird behavior and needs to be further investigated

**Comment by jaagut** [comment]
Outdated
