### ISSUE TITLE
our Wolfgang RoboCup Api can't handle ipv6 adresses

### ISSUE THREAD

**Issue by johagge** [bit-bots/bitbots_meta#249]
Our node for the RoboCup Api crashes when using an IPv6 adress as simulator IP.

## Expected behavior

We should probably use everything until the last ':' for host and only the last one as port.
If this is more complicated, I would be fine if this is closed as won't fix.

## Current behavior

File "/home/jonas/git/bitbots/bitbots_meta/rosws/src/bitbots_meta/wolfgang_robot/wolfgang_robocup_api/src/wolfgang_robocup_api/wolfgang_robocup_api.py", line 136, in get_connection
    host, port = addr.split(':')
ValueError: too many values to unpack (expected 2)

## Steps to Reproduce

1. set ROBOCUP_SIMULATOR_ADDR=some:ipv6:addr
2. rosrun wolfgang_robocup_api start.sh goalie 0
3. look at the error
...

## Context (Environment)

- [ ] RViz
- [X] Simulator
- [ ] Robot
- [ ] Local

**Comment by Flova** [comment]
Software not in use anymore
